# AOSP reads gps_debug.conf. Only configure long-term PSDS.
# Preserve native normal/realtime PSDS settings.
LONGTERM_PSDS_SERVER_1=https://pathcf.prod.xtracloud.cn/xtra3Mgrbeji.bin
SUPL_HOST=supl.qxwz.com
SUPL_PORT=7276
SUPL_VER=0x20000
